// landing/src/components/organization/SocialAccountsManager.tsx
import { useState, useEffect, useRef } from 'react'
import { useOrganization } from '@/hooks/useOrganization'
import { useToast } from '@/hooks/useToast'
import { listSocialAccounts, deleteSocialAccount, updateSocialAccount, refreshAccountToken, assignSocialAccount, unassignSocialAccount } from '@/services/socialAccountsApi'
import { Button } from '@/components/ui/Button'
import { EmptyState } from '@/components/ui/EmptyState'
import { ConfirmDialog } from '@/components/ui/ConfirmDialog'
import { Dialog } from '@/components/ui/Dialog'
import { Badge } from '@/components/ui/Badge'
import type { SocialAccount, OrganizationMember } from '@/types/organization'
import { Globe, Trash2, Instagram, MoreVertical, RefreshCw, XCircle, CheckCircle, Users, Plus, Search, Check } from 'lucide-react'

function getPlatformGradient(platform: string) {
  if (platform === 'instagram') return 'from-purple-500 to-pink-500'
  if (platform === 'tiktok') return 'from-zinc-900 to-zinc-700'
  if (platform === 'youtube') return 'from-red-500 to-red-600'
  return 'from-cyan-500 to-cyan-700'
}

function getPlatformIcon(platform: string) {
  if (platform === 'instagram') return Instagram
  return Globe
}

function formatRelativeDate(dateStr: string | undefined): string {
  if (!dateStr) return ''
  const date = new Date(dateStr)
  const now = new Date()
  const diffDays = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60 * 24))
  if (diffDays === 0) return 'today'
  if (diffDays === 1) return 'yesterday'
  if (diffDays < 7) return `${diffDays} days ago`
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`
  return date.toLocaleDateString()
}

function isTokenExpiringSoon(account: SocialAccount): boolean {
  if (!account.token_expires_at) return false
  const expiresAt = new Date(account.token_expires_at)
  const daysUntilExpiry = (expiresAt.getTime() - Date.now()) / (1000 * 60 * 60 * 24)
  return daysUntilExpiry < 7
}

function AccountActionsMenu({ account, onRefreshToken, onToggleActive, onDisconnect, onManageAssignments }: {
  account: SocialAccount
  onRefreshToken: (a: SocialAccount) => void
  onToggleActive: (a: SocialAccount, active: boolean) => void
  onDisconnect: (a: SocialAccount) => void
  onManageAssignments: (a: SocialAccount) => void
}) {
  const [open, setOpen] = useState(false)
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!open) return
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [open])

  return (
    <div ref={ref} className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="p-1.5 rounded-lg hover:bg-zinc-700 text-zinc-400 hover:text-white transition-colors"
      >
        <MoreVertical className="w-4 h-4" />
      </button>
      {open && (
        <div className="absolute right-0 top-full mt-1 w-48 bg-zinc-800 border border-zinc-700 rounded-lg shadow-xl z-50 py-1 overflow-hidden">
          <button
            onClick={() => { onManageAssignments(account); setOpen(false) }}
            className="flex items-center gap-2 w-full px-3 py-2 text-sm text-zinc-300 hover:bg-zinc-700 hover:text-white transition-colors"
          >
            <Users className="w-4 h-4" />
            Manage Access
          </button>
          <button
            onClick={() => { onRefreshToken(account); setOpen(false) }}
            className="flex items-center gap-2 w-full px-3 py-2 text-sm text-zinc-300 hover:bg-zinc-700 hover:text-white transition-colors"
          >
            <RefreshCw className="w-4 h-4" />
            Refresh Token
          </button>
          {account.is_active ? (
            <button
              onClick={() => { onToggleActive(account, false); setOpen(false) }}
              className="flex items-center gap-2 w-full px-3 py-2 text-sm text-zinc-300 hover:bg-zinc-700 hover:text-white transition-colors"
            >
              <XCircle className="w-4 h-4" />
              Deactivate
            </button>
          ) : (
            <button
              onClick={() => { onToggleActive(account, true); setOpen(false) }}
              className="flex items-center gap-2 w-full px-3 py-2 text-sm text-zinc-300 hover:bg-zinc-700 hover:text-white transition-colors"
            >
              <CheckCircle className="w-4 h-4" />
              Activate
            </button>
          )}
          <div className="border-t border-zinc-700 my-1" />
          <button
            onClick={() => { onDisconnect(account); setOpen(false) }}
            className="flex items-center gap-2 w-full px-3 py-2 text-sm text-red-400 hover:bg-zinc-700 transition-colors"
          >
            <Trash2 className="w-4 h-4" />
            Disconnect
          </button>
        </div>
      )}
    </div>
  )
}

function AssignmentsDialog({ account, open, onClose, organizationId, members, onUpdated }: {
  account: SocialAccount
  open: boolean
  onClose: () => void
  organizationId: string
  members: OrganizationMember[]
  onUpdated: () => void
}) {
  const [searchQuery, setSearchQuery] = useState('')
  const [assignedIds, setAssignedIds] = useState<Set<number>>(new Set())
  const [saving, setSaving] = useState(false)
  const toast = useToast()

  useEffect(() => {
    if (open && account.assignments) {
      setAssignedIds(new Set(account.assignments.map(a => a.user_id)))
    }
  }, [open, account])

  const filteredMembers = members.filter(m => {
    if (!searchQuery) return true
    const q = searchQuery.toLowerCase()
    return (m.user?.name?.toLowerCase().includes(q) || m.user?.email.toLowerCase().includes(q))
  })

  const toggleAssignment = async (userId: number, assign: boolean) => {
    setSaving(true)
    try {
      if (assign) {
        const res = await assignSocialAccount(organizationId, account.id, [userId])
        if (res.success) {
          setAssignedIds(prev => new Set([...prev, userId]))
          toast.success('Member assigned')
          onUpdated()
        } else { toast.error(res.error || 'Failed to assign') }
      } else {
        const res = await unassignSocialAccount(organizationId, account.id, userId)
        if (res.success) {
          setAssignedIds(prev => { const s = new Set(prev); s.delete(userId); return s })
          toast.success('Member unassigned')
          onUpdated()
        } else { toast.error(res.error || 'Failed to unassign') }
      }
    } catch { toast.error('Failed to update assignment') }
    finally { setSaving(false) }
  }

  const getInitials = (name: string) =>
    name.split(/[\s@]+/).map(p => p[0]).slice(0, 2).join('').toUpperCase()

  return (
    <Dialog open={open} onClose={onClose} title="Manage Access" maxWidth="max-w-lg">
      <div className="space-y-4">
        <div className="flex items-center gap-3 pb-3 border-b border-zinc-800">
          <div className={`w-10 h-10 rounded-xl flex items-center justify-center bg-gradient-to-br ${getPlatformGradient(account.platform)}/20 border border-pink-500/30`}>
            <Instagram className="w-5 h-5 text-pink-400" />
          </div>
          <div>
            <p className="text-sm font-medium text-white">@{account.username}</p>
            <p className="text-xs text-zinc-500">Assign members who can use this account to publish posts</p>
          </div>
        </div>

        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-500" />
          <input
            type="text"
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            placeholder="Search members..."
            className="w-full pl-10 pr-4 py-2.5 bg-zinc-900/80 border border-zinc-800 rounded-lg text-white placeholder-zinc-500 focus:outline-none focus:ring-2 focus:ring-pink-500/50 focus:border-pink-500/50 transition-all text-sm"
          />
        </div>

        <div className="space-y-1.5 max-h-[300px] overflow-y-auto">
          {filteredMembers.map(member => {
            const assigned = assignedIds.has(member.user_id)
            return (
              <button
                key={member.user_id}
                onClick={() => toggleAssignment(member.user_id, !assigned)}
                disabled={saving}
                className={`flex items-center gap-3 w-full p-3 rounded-xl border transition-colors text-left ${saving ? 'opacity-50 pointer-events-none' : ''} ${assigned ? 'border-zinc-700 bg-zinc-800/30' : 'border-zinc-800 hover:bg-zinc-800/50 hover:border-zinc-700'}`}
              >
                <div className={`w-5 h-5 rounded-md border-2 flex items-center justify-center shrink-0 transition-all ${assigned ? 'bg-gradient-to-r from-purple-500 to-pink-500 border-transparent' : 'border-zinc-600'}`}>
                  {assigned && <Check className="w-3 h-3 text-white" />}
                </div>
                <div className="w-9 h-9 rounded-full bg-zinc-800 flex items-center justify-center shrink-0 border border-zinc-700 overflow-hidden">
                  {member.user?.avatar_url ? (
                    <img src={member.user.avatar_url} alt="" className="w-9 h-9 rounded-full object-cover" />
                  ) : (
                    <span className="text-xs font-medium text-zinc-400">{getInitials(member.user?.name || member.user?.email || '')}</span>
                  )}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-medium text-white truncate">{member.user?.name || member.user?.email}</div>
                  {member.user?.name && <div className="text-xs text-zinc-500 truncate">{member.user.email}</div>}
                </div>
                <Badge variant={member.role === 'owner' ? 'owner' : member.role === 'admin' ? 'admin' : 'member'}>{member.role}</Badge>
              </button>
            )
          })}
          {filteredMembers.length === 0 && searchQuery && (
            <div className="text-center py-8">
              <Search className="w-5 h-5 text-zinc-500 mx-auto mb-2" />
              <p className="text-sm text-zinc-500">No members match your search</p>
            </div>
          )}
        </div>

        <div className="flex items-center justify-between pt-3 border-t border-zinc-800">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-pink-500" />
            <span className="text-sm text-zinc-400">{assignedIds.size} member{assignedIds.size !== 1 ? 's' : ''} assigned</span>
          </div>
          <Button variant="secondary" size="sm" onClick={onClose}>Done</Button>
        </div>
      </div>
    </Dialog>
  )
}

export function SocialAccountsManager() {
  const [accounts, setAccounts] = useState<SocialAccount[]>([])
  const [loading, setLoading] = useState(true)
  const [deleteTarget, setDeleteTarget] = useState<SocialAccount | null>(null)
  const [deleting, setDeleting] = useState(false)
  const [assignTarget, setAssignTarget] = useState<SocialAccount | null>(null)
  const { organizationId, isAdmin, members } = useOrganization()
  const toast = useToast()

  const load = async () => {
    if (!organizationId) return
    setLoading(true)
    try {
      const result = await listSocialAccounts(organizationId, true)
      if (result.success) setAccounts(result.accounts)
    } finally { setLoading(false) }
  }

  useEffect(() => { load() }, [organizationId])

  const handleDelete = async () => {
    if (!deleteTarget || !organizationId) return
    setDeleting(true)
    try {
      const result = await deleteSocialAccount(organizationId, deleteTarget.id)
      if (result.success) {
        setAccounts(prev => prev.filter(a => a.id !== deleteTarget.id))
        toast.success('Account disconnected')
      }
    } finally { setDeleting(false); setDeleteTarget(null) }
  }

  const handleToggleActive = async (account: SocialAccount, active: boolean) => {
    if (!organizationId) return
    try {
      const result = await updateSocialAccount(organizationId, account.id, { is_active: active })
      if (result.success) {
        toast.success(`Account ${active ? 'activated' : 'deactivated'}`)
        load()
      } else { toast.error(result.error || 'Failed to update account') }
    } catch { toast.error('Failed to update account') }
  }

  const handleRefreshToken = async (account: SocialAccount) => {
    if (!organizationId) return
    try {
      const result = await refreshAccountToken(organizationId, account.id)
      if (result.success) { toast.success('Token refresh initiated') }
      else { toast.error(result.error || 'Failed to refresh token') }
    } catch { toast.error('Failed to refresh token') }
  }

  if (loading) return (
    <div className="p-6 space-y-3 max-w-[1400px] mx-auto w-full">
      {[1, 2].map(i => (
        <div key={i} className="py-4 px-5 bg-zinc-800/20 border border-zinc-800/30 rounded-[10px] animate-pulse">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-full bg-zinc-800/50" />
            <div className="flex-1 space-y-2">
              <div className="h-4 w-32 bg-zinc-800/50 rounded" />
              <div className="h-3 w-48 bg-zinc-800/50 rounded" />
            </div>
          </div>
        </div>
      ))}
    </div>
  )

  if (accounts.length === 0) return (
    <EmptyState
      icon={Instagram}
      title="No Accounts Connected"
      description="Connect your Instagram account to start publishing clips directly"
      action={isAdmin && <Button onClick={() => toast.info('Use the desktop app to connect Instagram via OAuth')}><Plus className="w-4 h-4" /> Connect Account</Button>}
    />
  )

  return (
    <>
      <div className="p-6 space-y-3 max-w-[1400px] mx-auto w-full">
        {accounts.map(account => {
          const PlatformIcon = getPlatformIcon(account.platform)
          const gradient = getPlatformGradient(account.platform)
          return (
            <div key={account.id} className="py-4 px-5 bg-zinc-900/50 border border-zinc-800 rounded-[10px] hover:border-white/[0.12] transition-all hover:shadow-[0_4px_16px_rgba(0,0,0,0.15)]">
              <div className="flex items-center gap-4">
                {/* Avatar with platform badge */}
                <div className="relative shrink-0">
                  {account.profile_image_url ? (
                    <img src={account.profile_image_url} alt={account.username} className="w-12 h-12 rounded-full object-cover" />
                  ) : (
                    <div className={`w-12 h-12 rounded-full bg-gradient-to-br ${gradient} flex items-center justify-center`}>
                      <PlatformIcon className="w-6 h-6 text-white" />
                    </div>
                  )}
                  <div className={`absolute -bottom-1 -right-1 w-5 h-5 rounded-full bg-gradient-to-br ${gradient} flex items-center justify-center ring-2 ring-zinc-900`}>
                    <PlatformIcon className="w-3 h-3 text-white" />
                  </div>
                </div>

                {/* Account info */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-white">@{account.username}</span>
                    {!account.is_active && (
                      <span className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-red-500/20 text-red-400">Inactive</span>
                    )}
                    {account.is_active && isTokenExpiringSoon(account) && (
                      <span className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-amber-500/20 text-amber-400">Token expiring</span>
                    )}
                  </div>
                  <div className="text-sm text-zinc-500">{account.display_name || account.username}</div>
                  <div className="text-xs text-zinc-600 mt-0.5">
                    Connected {formatRelativeDate(account.inserted_at)}
                    {account.assignments && account.assignments.length > 0 && (
                      <> · {account.assignments.length} member{account.assignments.length !== 1 ? 's' : ''} assigned</>
                    )}
                  </div>
                </div>

                {/* Actions */}
                {isAdmin && (
                  <div className="flex items-center gap-1 shrink-0">
                    <button
                      onClick={() => setAssignTarget(account)}
                      className="p-2 rounded-lg hover:bg-zinc-700 text-zinc-400 hover:text-white transition-colors"
                      title="Manage assignments"
                    >
                      <Users className="w-4 h-4" />
                    </button>
                    <AccountActionsMenu
                      account={account}
                      onRefreshToken={handleRefreshToken}
                      onToggleActive={handleToggleActive}
                      onDisconnect={setDeleteTarget}
                      onManageAssignments={setAssignTarget}
                    />
                  </div>
                )}
              </div>
            </div>
          )
        })}
      </div>

      {/* Assignments Dialog */}
      {assignTarget && (
        <AssignmentsDialog
          account={assignTarget}
          open={!!assignTarget}
          onClose={() => setAssignTarget(null)}
          organizationId={organizationId}
          members={members}
          onUpdated={load}
        />
      )}

      {/* Delete Confirmation */}
      <ConfirmDialog
        open={!!deleteTarget}
        onClose={() => setDeleteTarget(null)}
        onConfirm={handleDelete}
        title="Disconnect Account"
        description={`Are you sure you want to disconnect @${deleteTarget?.username}? This will remove all member assignments. Any existing posts will remain but won't be synced.`}
        confirmText="Disconnect"
        loading={deleting}
      />
    </>
  )
}

// client/src/components/organization/SocialAccountsManager.vue
<template>
  <div class="space-y-6">
    <!-- Header -->
    <div class="flex items-center justify-between">
      <div>
        <h2 class="text-base font-semibold text-foreground">Connected Accounts</h2>
        <p class="text-sm text-muted-foreground mt-0.5">Connect social media accounts to publish clips directly</p>
      </div>
      <Button v-if="isAdmin" size="sm" @click="connectInstagram" :disabled="connecting">
        <Instagram class="h-4 w-4 mr-1.5" />
        {{ connecting ? 'Connecting...' : 'Connect Instagram' }}
      </Button>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="space-y-3">
      <div v-for="i in 2" :key="i" class="p-4 bg-muted/20 border border-border/30 rounded-lg animate-pulse">
        <div class="flex items-center gap-4">
          <div class="w-12 h-12 rounded-full bg-muted/50"></div>
          <div class="flex-1 space-y-2">
            <div class="h-4 w-32 bg-muted/50 rounded"></div>
            <div class="h-3 w-48 bg-muted/50 rounded"></div>
          </div>
        </div>
      </div>
    </div>

    <!-- Empty State -->
    <div v-else-if="accounts.length === 0" class="text-center py-12 border border-dashed border-border rounded-lg">
      <Instagram class="h-12 w-12 text-muted-foreground mx-auto mb-4" />
      <h3 class="text-sm font-medium text-foreground mb-1">No accounts connected</h3>
      <p class="text-sm text-muted-foreground mb-4">Connect your Instagram account to start publishing clips</p>
      <Button v-if="isAdmin" size="sm" @click="connectInstagram" :disabled="connecting">
        <Plus class="h-4 w-4 mr-1.5" />
        Connect Account
      </Button>
    </div>

    <!-- Accounts List -->
    <div v-else class="space-y-3">
      <div
        v-for="account in accounts"
        :key="account.id"
        class="p-4 bg-card border border-border rounded-lg hover:border-border/80 transition-colors"
      >
        <div class="flex items-center gap-4">
          <!-- Account Avatar -->
          <div class="relative flex-shrink-0">
            <img
              v-if="account.profile_image_url"
              :src="account.profile_image_url"
              :alt="account.username"
              class="w-12 h-12 rounded-full object-cover"
            />
            <div
              v-else
              class="w-12 h-12 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center"
            >
              <Instagram class="h-6 w-6 text-white" />
            </div>
            <!-- Platform badge -->
            <div
              class="absolute -bottom-1 -right-1 w-5 h-5 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center ring-2 ring-background"
            >
              <Instagram class="h-3 w-3 text-white" />
            </div>
          </div>

          <!-- Account Info -->
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2">
              <span class="font-medium text-foreground">@{{ account.username }}</span>
              <span v-if="!account.is_active" class="px-1.5 py-0.5 rounded text-xs bg-destructive/20 text-destructive">
                Inactive
              </span>
              <span
                v-else-if="isTokenExpiringSoon(account)"
                class="px-1.5 py-0.5 rounded text-xs bg-amber-500/20 text-amber-500"
              >
                Token expiring
              </span>
            </div>
            <div class="text-sm text-muted-foreground">
              {{ account.display_name || account.username }}
            </div>
            <div class="text-xs text-muted-foreground mt-1">
              Connected {{ formatDate(account.connected_at) }}
              <template v-if="account.assignments?.length">
                · {{ account.assignments.length }} member{{ account.assignments.length !== 1 ? 's' : '' }} assigned
              </template>
            </div>
          </div>

          <!-- Actions -->
          <div v-if="isAdmin" class="flex items-center gap-2">
            <Button variant="ghost" size="sm" @click="openAssignments(account)" title="Manage assignments">
              <Users class="h-4 w-4" />
            </Button>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="sm">
                  <MoreVertical class="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem @click="refreshToken(account)">
                  <RefreshCw class="h-4 w-4 mr-2" />
                  Refresh Token
                </DropdownMenuItem>
                <DropdownMenuItem v-if="account.is_active" @click="toggleActive(account, false)">
                  <XCircle class="h-4 w-4 mr-2" />
                  Deactivate
                </DropdownMenuItem>
                <DropdownMenuItem v-else @click="toggleActive(account, true)">
                  <CheckCircle class="h-4 w-4 mr-2" />
                  Activate
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem class="text-destructive focus:text-destructive" @click="confirmDelete(account)">
                  <Trash2 class="h-4 w-4 mr-2" />
                  Disconnect
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </div>
    </div>

    <!-- Assignments Dialog -->
    <SocialAccountAssignments
      v-if="selectedAccount"
      :account="selectedAccount"
      :organization-id="organizationId"
      :members="members"
      :open="showAssignmentsDialog"
      @close="showAssignmentsDialog = false"
      @updated="loadAccounts"
    />

    <!-- Delete Confirmation Dialog -->
    <Dialog :open="showDeleteDialog" @update:open="showDeleteDialog = $event">
      <DialogContent class="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle class="flex items-center gap-2">
            <Trash2 class="h-5 w-5 text-destructive" />
            Disconnect Account
          </DialogTitle>
          <DialogDescription>
            Are you sure you want to disconnect @{{ accountToDelete?.username }}? This will remove all member
            assignments and any posts will remain but won't be synced.
          </DialogDescription>
        </DialogHeader>
        <DialogFooter class="gap-2 sm:gap-0">
          <Button variant="outline" @click="showDeleteDialog = false">Cancel</Button>
          <Button variant="destructive" @click="deleteAccount">Disconnect</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
  import { ref, computed, onMounted, onUnmounted } from 'vue';
  import { Button } from '@/components/ui/button';
  import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
  } from '@/components/ui/dropdown-menu';
  import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
  } from '@/components/ui/dialog';
  import { Instagram, Plus, Users, MoreVertical, RefreshCw, XCircle, CheckCircle, Trash2 } from 'lucide-vue-next';
  import { useToast } from '@/composables/useToast';
  import SocialAccountAssignments from './SocialAccountAssignments.vue';
  import {
    listSocialAccounts,
    startInstagramOAuthPopup,
    updateSocialAccount,
    deleteSocialAccount,
    refreshAccountToken,
    type SocialAccount,
  } from '@/services/socialAccountsApi';

  interface Member {
    id: number;
    user_id: number;
    role: string;
    user: {
      id: number;
      email: string;
      name: string | null;
      avatar_url: string | null;
    };
  }

  const props = defineProps<{
    organizationId: string | number;
    isAdmin: boolean;
    members: Member[];
  }>();

  const emit = defineEmits<{
    (e: 'accountsChanged'): void;
  }>();

  const { showToast } = useToast();

  const loading = ref(true);
  const connecting = ref(false);
  const accounts = ref<SocialAccount[]>([]);
  const selectedAccount = ref<SocialAccount | null>(null);
  const showAssignmentsDialog = ref(false);
  const showDeleteDialog = ref(false);
  const accountToDelete = ref<SocialAccount | null>(null);

  // Cleanup function for OAuth listener
  let cleanupAuthListener: (() => void) | null = null;

  onMounted(() => {
    loadAccounts();
  });

  // Clean up listener on unmount
  onUnmounted(() => {
    if (cleanupAuthListener) {
      cleanupAuthListener();
    }
  });

  async function handleAuthResult(result: { success: boolean; account?: any; error?: string }) {
    if (result.success && result.account) {
      showToast(`Instagram account @${result.account.username} connected successfully`, 'success');
      await loadAccounts();
      emit('accountsChanged');
    } else if (result.error) {
      showToast(result.error, 'error');
    }
    connecting.value = false;
  }

  async function loadAccounts() {
    loading.value = true;
    try {
      const response = await listSocialAccounts(props.organizationId, true);
      if (response.success) {
        accounts.value = response.accounts;
      } else {
        showToast('Failed to load accounts', 'error');
      }
    } catch (error) {
      console.error('Failed to load accounts:', error);
      showToast('Failed to load accounts', 'error');
    } finally {
      loading.value = false;
    }
  }

  async function connectInstagram() {
    connecting.value = true;
    try {
      // Open Instagram OAuth via Tauri
      // The result will be handled by the onInstagramAuthComplete listener or the callback
      cleanupAuthListener = await startInstagramOAuthPopup(props.organizationId, handleAuthResult);
    } catch (error) {
      console.error('Failed to connect Instagram:', error);
      showToast(error instanceof Error ? error.message : 'Failed to connect Instagram.', 'error');
      connecting.value = false;
    }
  }

  function openAssignments(account: SocialAccount) {
    selectedAccount.value = account;
    showAssignmentsDialog.value = true;
  }

  async function toggleActive(account: SocialAccount, active: boolean) {
    try {
      const response = await updateSocialAccount(props.organizationId, account.id, {
        is_active: active,
      });

      if (response.success) {
        showToast(`Account ${active ? 'activated' : 'deactivated'}`, 'success');
        await loadAccounts();
      } else {
        showToast(response.error || 'Failed to update account', 'error');
      }
    } catch (error) {
      console.error('Failed to toggle account:', error);
      showToast('Failed to update account', 'error');
    }
  }

  async function refreshToken(account: SocialAccount) {
    try {
      const response = await refreshAccountToken(props.organizationId, account.id);
      if (response.success) {
        showToast('Token refresh initiated', 'success');
      } else {
        showToast(response.error || 'Failed to refresh token', 'error');
      }
    } catch (error) {
      console.error('Failed to refresh token:', error);
      showToast('Failed to refresh token', 'error');
    }
  }

  function confirmDelete(account: SocialAccount) {
    accountToDelete.value = account;
    showDeleteDialog.value = true;
  }

  async function deleteAccount() {
    if (!accountToDelete.value) return;

    try {
      const response = await deleteSocialAccount(props.organizationId, accountToDelete.value.id);
      if (response.success) {
        showToast('Account disconnected', 'success');
        await loadAccounts();
        emit('accountsChanged');
      } else {
        showToast(response.error || 'Failed to disconnect account', 'error');
      }
    } catch (error) {
      console.error('Failed to delete account:', error);
      showToast('Failed to disconnect account', 'error');
    } finally {
      showDeleteDialog.value = false;
      accountToDelete.value = null;
    }
  }

  function isTokenExpiringSoon(account: SocialAccount): boolean {
    if (!account.token_expires_at) return false;
    const expiresAt = new Date(account.token_expires_at);
    const daysUntilExpiry = (expiresAt.getTime() - Date.now()) / (1000 * 60 * 60 * 24);
    return daysUntilExpiry < 7;
  }

  function formatDate(dateString: string): string {
    const date = new Date(dateString);
    const now = new Date();
    const diffDays = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60 * 24));

    if (diffDays === 0) return 'today';
    if (diffDays === 1) return 'yesterday';
    if (diffDays < 7) return `${diffDays} days ago`;
    if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`;
    return date.toLocaleDateString();
  }
</script>
