// apps/mobile/src/editor/templates/TemplatePreview.tsx
import { templatePreviewLook, type TemplateManifest } from '@clippster/template-schema'
import { Text, View } from 'react-native'

/**
 * TikTok Instant Edit / Templates-style portrait tile: 9:16 preview with
 * bottom scrim, name, and clip-count — labels live on the media, not under it.
 */
export function TemplatePreview({
  manifest,
  featured = false,
  showMeta = true
}: {
  manifest: TemplateManifest
  featured?: boolean
  showMeta?: boolean
}) {
  const look = templatePreviewLook(manifest)
  const titleTop = look.titlePosition === 'top' ? '14%' : look.titlePosition === 'bottom' ? '58%' : '40%'
  const plates = Array.from({ length: look.plateCount }, (_, index) => index)
  const clipLabel = `${look.slotCount} clip${look.slotCount === 1 ? '' : 's'}`

  return (
    <View className="flex-1 overflow-hidden" style={{ backgroundColor: look.gradientTo }}>
      <View className="absolute inset-0" style={{ backgroundColor: look.gradientFrom, opacity: 0.78 }} />
      <View
        className="absolute left-1/2 h-[42%] w-[42%] -translate-x-1/2 rounded-full"
        style={{ top: '16%', backgroundColor: `${look.accentColor}66` }}
      />
      <View className="absolute inset-x-[14%] bottom-[28%] h-[34%] rounded-t-[48px] bg-black/40" />
      {look.plateCount > 1 ? (
        <View className="absolute inset-x-2 top-[62%] h-1.5 flex-row gap-0.5">
          {plates.map((index) => (
            <View
              key={index}
              className="h-full flex-1 rounded-sm bg-white/30"
              style={{ opacity: 0.35 + (index + 1) * 0.12 }}
            />
          ))}
        </View>
      ) : null}
      {look.effectLabel === 'Vignette' ? <View className="absolute inset-0 bg-black/30" /> : null}
      <Text
        numberOfLines={1}
        className="absolute inset-x-2 text-center text-white"
        style={{
          top: titleTop,
          fontSize: featured ? 18 : 11,
          fontWeight: look.titleStyle === 'clean' ? '600' : '800',
          letterSpacing: look.titleStyle === 'documentary' ? 1.2 : 0,
          backgroundColor: look.titleStyle === 'label' ? look.accentColor : 'transparent',
          paddingHorizontal: look.titleStyle === 'label' ? 6 : 0,
          overflow: 'hidden'
        }}
      >
        {look.titleText}
      </Text>
      {showMeta ? (
        <>
          <View className="absolute inset-x-0 bottom-0 h-[42%] bg-black/55" />
          <View className="absolute inset-x-0 bottom-0 px-2 pb-2 pt-6">
            <Text numberOfLines={1} className="text-[11px] font-semibold text-white">
              {look.name}
            </Text>
            <Text numberOfLines={1} className="mt-0.5 text-[10px] text-white/75">
              {clipLabel} · {look.durationLabel}
            </Text>
          </View>
          <View className="absolute left-1.5 top-1.5 rounded-full bg-black/55 px-1.5 py-0.5">
            <Text className="text-[9px] font-semibold text-white/90">{clipLabel}</Text>
          </View>
        </>
      ) : null}
    </View>
  )
}

// client/src/editor/components/panels/assets/TemplatePreview.vue
<script setup lang="ts">
import { computed } from 'vue';
import { templatePreviewLook, type TemplateManifest } from '@clippster/template-schema';

const props = defineProps<{
  manifest: TemplateManifest;
  featured?: boolean;
}>();

const look = computed(() => templatePreviewLook(props.manifest));

const titleClass = computed(() => {
  const style = look.value.titleStyle;
  if (style === 'bold' || style === 'neon') return 'font-black tracking-wide uppercase';
  if (style === 'documentary') return 'font-semibold uppercase tracking-[0.18em]';
  if (style === 'label') return 'rounded-sm px-1 font-bold uppercase';
  return 'font-semibold';
});

const titleTop = computed(() => {
  if (look.value.titlePosition === 'top') return '12%';
  if (look.value.titlePosition === 'bottom') return '72%';
  return '42%';
});
</script>

<template>
  <div
    class="relative overflow-hidden bg-zinc-950"
    :class="featured ? 'aspect-video' : 'aspect-[4/3]'"
    :style="{ background: `linear-gradient(160deg, ${look.gradientFrom}, ${look.gradientTo})` }"
  >
    <div
      class="absolute inset-0 opacity-80"
      :style="{ filter: look.cssFilter }"
    >
      <div
        class="absolute left-1/2 top-[18%] h-[38%] w-[34%] -translate-x-1/2 rounded-full"
        :style="{ background: `${look.accentColor}33` }"
      />
      <div class="absolute inset-x-[18%] bottom-[22%] h-[28%] rounded-t-[40%] bg-black/35" />
      <div
        v-if="look.plateCount > 1"
        class="absolute inset-x-1.5 bottom-1.5 flex h-2.5 gap-0.5"
      >
        <span
          v-for="index in look.plateCount"
          :key="index"
          class="h-full flex-1 rounded-[2px] bg-white/25"
          :style="{ opacity: 0.35 + index * 0.12 }"
        />
      </div>
    </div>
    <div
      v-if="look.effectLabel === 'Vignette'"
      class="pointer-events-none absolute inset-0 shadow-[inset_0_0_28px_12px_rgba(0,0,0,0.55)]"
    />
    <div
      class="absolute inset-x-1 text-center text-white drop-shadow"
      :class="titleClass"
      :style="{
        top: titleTop,
        fontSize: featured ? '11px' : '8px',
        backgroundColor: look.titleStyle === 'label' ? look.accentColor : undefined,
      }"
    >
      {{ look.titleText }}
    </div>
    <div
      class="absolute left-1.5 top-1.5 max-w-[70%] truncate rounded bg-black/55 px-1 py-0.5 text-[8px] text-white/90"
    >
      {{ look.actionLabel }}
    </div>
  </div>
</template>
