// client/src/pages/CampaignDetailPage.vue
<template>
  <div class="campaign-detail">
    <PageLayout
      :title="campaign?.title || 'Campaign'"
      :description="campaign?.description || 'Campaign details and management'"
      :show-header="true"
      :icon="Megaphone"
    >
      <template #actions>
        <button v-if="campaign && isAdmin" class="edit-btn" @click="editCampaign">
          <Pencil class="edit-btn__icon" />
          Edit Campaign
        </button>
      </template>

      <Breadcrumbs :items="breadcrumbItems" />

      <!-- Loading State -->
      <div v-if="loading" class="campaign-detail__loading">
        <div class="skeleton-header"></div>
        <div class="skeleton-tabs"></div>
        <div class="skeleton-content"></div>
      </div>

      <!-- Campaign Content -->
      <div v-else-if="campaign" class="campaign-page">
        <!-- Enhanced Campaign Header -->
        <div class="campaign-header-card">
          <div class="campaign-header-bg" :style="campaign.cover_image_url ? { backgroundImage: `url(${campaign.cover_image_url})` } : {}"></div>
          <div class="campaign-header-content">
            <div class="campaign-header-main">
              <div class="campaign-avatar-wrapper">
                <div class="campaign-avatar">
                  <img
                    v-if="campaign.cover_image_url"
                    :src="campaign.cover_image_url"
                    class="campaign-avatar__img"
                  />
                  <Megaphone v-else class="campaign-avatar__fallback" />
                </div>
              </div>
              <div class="campaign-info">
                <div class="campaign-name-row">
                  <h1 class="campaign-name">{{ campaign.title }}</h1>
                  <div class="campaign-badges">
                    <span class="status-badge" :class="`status-badge--${campaign.status}`">
                      {{ campaign.status.toUpperCase() }}
                    </span>
                    <span v-if="campaign.payment_model === 'per_clip'" class="status-badge status-badge--per-clip">
                      <DollarSign :size="12" />
                      Per Clip
                    </span>
                    <span v-else class="status-badge status-badge--cpm">
                      <TrendingUp :size="12" />
                      CPM
                    </span>
                  </div>
                </div>
                <div class="campaign-meta-row">
                  <span v-if="campaign.organization" class="campaign-org">
                    <Building2 :size="14" />
                    {{ campaign.organization.name }}
                  </span>
                  <span v-if="campaign.starts_at" class="campaign-dates">
                    <Calendar :size="14" />
                    {{ formatDate(campaign.starts_at) }} - {{ campaign.ends_at ? formatDate(campaign.ends_at) : 'Ongoing' }}
                  </span>
                </div>
                <p class="campaign-bio">
                  {{ campaign.description || 'No description provided' }}
                </p>
                <div v-if="campaign.allowed_platforms?.length" class="campaign-platforms">
                  <span v-for="platform in campaign.allowed_platforms" :key="platform" class="campaign-platform-tag">
                    {{ getPlatformDisplayName(platform) }}
                  </span>
                </div>
              </div>
            </div>
            <div class="campaign-stats-grid">
              <div class="campaign-stat-card">
                <div class="campaign-stat-card__icon campaign-stat-card__icon--purple">
                  <Users :size="18" />
                </div>
                <div class="campaign-stat-card__content">
                  <span class="campaign-stat-card__value">{{ stats.participants_count || 0 }}</span>
                  <span class="campaign-stat-card__label">Participants</span>
                </div>
              </div>
              <div class="campaign-stat-card">
                <div class="campaign-stat-card__icon campaign-stat-card__icon--cyan">
                  <FileVideo :size="18" />
                </div>
                <div class="campaign-stat-card__content">
                  <span class="campaign-stat-card__value">{{ stats.submissions_count || 0 }}</span>
                  <span class="campaign-stat-card__label">Submissions</span>
                </div>
              </div>
              <div class="campaign-stat-card">
                <div class="campaign-stat-card__icon campaign-stat-card__icon--green">
                  <CheckCircle :size="18" />
                </div>
                <div class="campaign-stat-card__content">
                  <span class="campaign-stat-card__value">{{ stats.verified_count || 0 }}</span>
                  <span class="campaign-stat-card__label">Verified</span>
                </div>
              </div>
              <div class="campaign-stat-card">
                <div class="campaign-stat-card__icon campaign-stat-card__icon--orange">
                  <Wallet :size="18" />
                </div>
                <div class="campaign-stat-card__content">
                  <span class="campaign-stat-card__value">${{ formatBudget(campaign.spent_budget || 0) }}</span>
                  <span class="campaign-stat-card__label">Spent</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Budget Progress Bar -->
        <div class="budget-card">
          <div class="budget-card__header">
            <div class="budget-card__title">
              <Wallet :size="18" />
              <span>Budget Usage</span>
            </div>
            <span class="budget-card__amount">
              ${{ formatBudget(campaign.spent_budget || 0) }} / ${{ formatBudget(campaign.budget) }}
            </span>
          </div>
          <div class="budget-card__bar">
            <div
              class="budget-card__fill"
              :style="{ width: getBudgetPercentage() + '%' }"
              :class="{
                'budget-card__fill--low': getBudgetPercentage() < 50,
                'budget-card__fill--medium': getBudgetPercentage() >= 50 && getBudgetPercentage() < 80,
                'budget-card__fill--high': getBudgetPercentage() >= 80,
              }"
            ></div>
          </div>
          <div class="budget-card__footer">
            <span class="budget-card__remaining">
              ${{ formatBudget(getRemainingBudget()) }} remaining
            </span>
            <span class="budget-card__percentage">
              {{ getBudgetPercentage().toFixed(1) }}% used
            </span>
          </div>
        </div>

        <!-- Enhanced Tab Navigation -->
        <nav class="tabs-nav">
          <div class="tabs-container">
            <button
              v-for="tab in tabs"
              :key="tab.id"
              class="tab-button"
              :class="{ 'tab-button--active': activeTab === tab.id }"
              @click="activeTab = tab.id"
            >
              <div class="tab-button__icon">
                <component :is="tab.icon" />
              </div>
              <span class="tab-button__label">{{ tab.label }}</span>
              <span v-if="tab.count !== undefined" class="tab-button__count">{{ tab.count }}</span>
            </button>
          </div>
        </nav>

        <!-- Content -->
        <main class="content">
          <!-- Overview Tab -->
          <template v-if="activeTab === 'overview'">
            <div class="overview-section">
              <h2 class="section-title">Campaign Details</h2>
              <div class="details-grid">
                <div class="detail-item">
                  <span class="detail-label">Payment Model</span>
                  <span class="detail-value">{{ campaign.payment_model === 'per_clip' ? 'Pay Per Clip' : 'CPM (Cost Per Mille)' }}</span>
                </div>
                <div class="detail-item">
                  <span class="detail-label">{{ campaign.payment_model === 'per_clip' ? 'Amount Per Clip' : 'CPM Rate' }}</span>
                  <span class="detail-value">${{ campaign.payment_model === 'per_clip' ? formatBudget(campaign.per_clip_amount || 0) : formatCpm(campaign.cpm) }}</span>
                </div>
                <div class="detail-item">
                  <span class="detail-label">Min Views for Payment</span>
                  <span class="detail-value">{{ formatViews(campaign.min_views_for_payment) }}</span>
                </div>
                <div v-if="campaign.max_views" class="detail-item">
                  <span class="detail-label">Max Views Cap</span>
                  <span class="detail-value">{{ formatViews(campaign.max_views) }}</span>
                </div>
                <div class="detail-item">
                  <span class="detail-label">Join Type</span>
                  <span class="detail-value">{{ campaign.join_type === 'open' ? 'Open to All' : 'Application Required' }}</span>
                </div>
              </div>
            </div>

            <div class="overview-section">
              <h2 class="section-title">Streamers to Clip</h2>
              <div v-if="!campaign.creator_profile_id && (!campaign.assigned_streamer_ids || campaign.assigned_streamer_ids.length === 0)" class="global-branding-notice">
                <div class="global-branding-notice__icon">
                  <Globe :size="24" />
                </div>
                <div class="global-branding-notice__content">
                  <h3 class="global-branding-notice__title">Any Streamers Qualify</h3>
                  <p class="global-branding-notice__description">
                    This campaign uses global branding. Clippers can create clips from any streamer, and the organization's branding will be applied automatically.
                  </p>
                </div>
              </div>
              <div v-else-if="campaign.creator_profile_id" class="creator-profile-info">
                <p class="text-sm text-gray-400 mb-4">This campaign is assigned to a specific creator profile:</p>
                <div v-if="campaign.creator_profile" class="p-4 bg-gray-800 border border-gray-700 rounded-lg">
                  <div class="flex items-center gap-3">
                    <img v-if="campaign.creator_profile.profile_image_url" :src="campaign.creator_profile.profile_image_url" class="w-12 h-12 rounded-full" />
                    <div>
                      <div class="font-semibold">{{ campaign.creator_profile.name }}</div>
                      <div class="text-sm text-gray-400">Creator Profile</div>
                    </div>
                  </div>
                </div>
                <div v-else class="p-4 bg-gray-800 border border-gray-700 rounded-lg text-center text-gray-400 text-sm">
                  Creator profile assigned
                </div>
              </div>
              <div v-else class="streamers-list">
                <p class="streamers-list__description">Clippers can only create clips from the following streamers:</p>
                <div class="streamers-list__placeholder">
                  {{ campaign.assigned_streamer_ids.length }} streamer(s) assigned
                </div>
              </div>
            </div>
          </template>

          <!-- Submissions Tab -->
          <template v-if="activeTab === 'submissions'">
            <div class="submissions-placeholder">
              <FileVideo :size="48" />
              <p>Submissions management coming soon</p>
            </div>
          </template>

          <!-- Participants Tab -->
          <template v-if="activeTab === 'participants'">
            <div class="participants-placeholder">
              <Users :size="48" />
              <p>Participants list coming soon</p>
            </div>
          </template>

          <!-- Payments Tab -->
          <template v-if="activeTab === 'payments'">
            <div class="payments-placeholder">
              <DollarSign :size="48" />
              <p>Payments management coming soon</p>
            </div>
          </template>
        </main>
      </div>

      <!-- Error State -->
      <div v-else class="campaign-detail__error">
        <AlertCircle :size="48" />
        <h3>Campaign not found</h3>
        <p>The campaign you're looking for doesn't exist or you don't have access to it.</p>
        <button class="back-btn" @click="$router.back()">Go Back</button>
      </div>
    </PageLayout>
  </div>
</template>

<script setup lang="ts">
  import { ref, computed, onMounted } from 'vue';
  import { useRoute, useRouter } from 'vue-router';
  import {
    Megaphone,
    Pencil,
    Building2,
    Users,
    FileVideo,
    CheckCircle,
    Wallet,
    DollarSign,
    TrendingUp,
    Calendar,
    AlertCircle,
    Globe,
  } from 'lucide-vue-next';
  import PageLayout from '@/components/PageLayout.vue';
  import Breadcrumbs from '@/components/Breadcrumbs.vue';
  import { getCampaign, getPlatformDisplayName, type Campaign, type CampaignStats } from '@/services/campaignApi';
  import { useToast } from '@/composables/useToast';
  import { useAuthStore } from '@/stores/auth';

  const route = useRoute();
  const router = useRouter();
  const { toast } = useToast();
  const authStore = useAuthStore();

  const breadcrumbItems = computed(() => [
    { label: 'Organizations', to: '/organizations' },
    { label: campaign.value?.organization?.name || 'Organization', to: `/organization/${route.params.orgId}` },
    { label: 'Campaigns', to: `/organization/${route.params.orgId}/campaigns` },
    { label: campaign.value?.title || 'Campaign' }
  ]);

  const loading = ref(true);
  const campaign = ref<Campaign | null>(null);
  const stats = ref<CampaignStats>({
    participants_count: 0,
    submissions_count: 0,
    verified_count: 0,
    total_views: 0,
    total_paid: '0',
  });
  const activeTab = ref('overview');

  const isAdmin = computed(() => {
    // TODO: Check if user is admin of the organization
    return true;
  });

  const tabs = computed(() => [
    { id: 'overview', label: 'Overview', icon: Megaphone },
    { id: 'submissions', label: 'Submissions', icon: FileVideo, count: stats.value.submissions_count },
    { id: 'participants', label: 'Participants', icon: Users, count: stats.value.participants_count },
    { id: 'payments', label: 'Payments', icon: DollarSign },
  ]);

  const formatBudget = (budget: string | number) => {
    const value = typeof budget === 'string' ? parseFloat(budget) : budget;
    if (value >= 1000) {
      return `${(value / 1000).toFixed(1)}K`;
    }
    return value.toFixed(0);
  };

  const formatCpm = (cpm: string | number) => {
    const value = typeof cpm === 'string' ? parseFloat(cpm) : cpm;
    return value.toFixed(2);
  };

  const formatViews = (views: number) => {
    if (views >= 1000000) {
      return `${(views / 1000000).toFixed(1)}M`;
    }
    if (views >= 1000) {
      return `${(views / 1000).toFixed(1)}K`;
    }
    return views.toString();
  };

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const getBudgetPercentage = () => {
    if (!campaign.value) return 0;
    const spent = parseFloat(campaign.value.spent_budget || '0');
    const budget = parseFloat(campaign.value.budget || '0');
    if (budget === 0) return 0;
    return Math.min((spent / budget) * 100, 100);
  };

  const getRemainingBudget = () => {
    if (!campaign.value) return 0;
    const spent = parseFloat(campaign.value.spent_budget || '0');
    const budget = parseFloat(campaign.value.budget || '0');
    return Math.max(budget - spent, 0);
  };

  const editCampaign = () => {
    router.push(`/organizations/${route.params.orgId}/campaigns`);
  };

  const loadCampaign = async () => {
    try {
      loading.value = true;
      const campaignId = parseInt(route.params.campaignId as string, 10);
      
      const response = await getCampaign(campaignId);
      if (response.success && response.campaign) {
        campaign.value = response.campaign;
        // TODO: Load stats from separate API endpoint when available
      } else {
        toast({ title: 'Error', description: 'Failed to load campaign' });
      }
    } catch (error) {
      console.error('Failed to load campaign:', error);
      toast({ title: 'Error', description: 'Failed to load campaign' });
    } finally {
      loading.value = false;
    }
  };

  onMounted(() => {
    loadCampaign();
  });
</script>

<style scoped>
  /* Base Layout */
  .campaign-detail {
    width: 100%;
    min-height: 100%;
  }

  .campaign-page {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  /* Loading & Error States */
  .campaign-detail__loading,
  .campaign-detail__error {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 4rem 2rem;
    gap: 1rem;
    color: var(--sidebar-text-muted);
  }

  .campaign-detail__error h3 {
    font-size: 1.25rem;
    font-weight: 600;
    color: var(--sidebar-text);
    margin: 0;
  }

  .back-btn {
    margin-top: 1rem;
    padding: 0.625rem 1.25rem;
    background: var(--sidebar-hover);
    border: 1px solid var(--sidebar-border);
    border-radius: 8px;
    color: var(--sidebar-text);
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s;
  }

  .back-btn:hover {
    background: var(--sidebar-active);
  }

  /* Header Card */
  .campaign-header-card {
    position: relative;
    background: var(--sidebar-bg);
    border: 1px solid var(--sidebar-border);
    border-radius: 16px;
    overflow: hidden;
  }

  .campaign-header-bg {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 120px;
    background: linear-gradient(135deg, rgba(59, 130, 246, 0.1) 0%, rgba(147, 51, 234, 0.1) 100%);
    background-size: cover;
    background-position: center;
    filter: blur(8px);
    opacity: 0.3;
  }

  .campaign-header-content {
    position: relative;
    padding: 2rem;
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .campaign-header-main {
    display: flex;
    gap: 1.5rem;
    align-items: flex-start;
  }

  .campaign-avatar-wrapper {
    flex-shrink: 0;
  }

  .campaign-avatar {
    position: relative;
    width: 96px;
    height: 96px;
    border-radius: 16px;
    background: var(--sidebar-hover);
    border: 3px solid var(--sidebar-bg);
    overflow: hidden;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .campaign-avatar__img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .campaign-avatar__fallback {
    width: 48px;
    height: 48px;
    color: var(--sidebar-text-muted);
  }

  .campaign-info {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .campaign-name-row {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    flex-wrap: wrap;
  }

  .campaign-name {
    font-size: 1.75rem;
    font-weight: 700;
    color: var(--sidebar-text);
    margin: 0;
    letter-spacing: -0.02em;
  }

  .campaign-badges {
    display: flex;
    gap: 0.5rem;
    flex-wrap: wrap;
  }

  .status-badge {
    display: inline-flex;
    align-items: center;
    gap: 0.25rem;
    padding: 0.25rem 0.625rem;
    border-radius: 6px;
    font-size: 0.6875rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.03em;
  }

  .status-badge--active {
    background: rgba(16, 185, 129, 0.15);
    color: #10b981;
    border: 1px solid rgba(16, 185, 129, 0.3);
  }

  .status-badge--draft {
    background: rgba(156, 163, 175, 0.15);
    color: #9ca3af;
    border: 1px solid rgba(156, 163, 175, 0.3);
  }

  .status-badge--paused {
    background: rgba(245, 158, 11, 0.15);
    color: #f59e0b;
    border: 1px solid rgba(245, 158, 11, 0.3);
  }

  .status-badge--completed {
    background: rgba(59, 130, 246, 0.15);
    color: #3b82f6;
    border: 1px solid rgba(59, 130, 246, 0.3);
  }

  .status-badge--per-clip,
  .status-badge--cpm {
    background: rgba(147, 51, 234, 0.15);
    color: #9333ea;
    border: 1px solid rgba(147, 51, 234, 0.3);
  }

  .campaign-meta-row {
    display: flex;
    align-items: center;
    gap: 1rem;
    flex-wrap: wrap;
    font-size: 0.875rem;
    color: var(--sidebar-text-muted);
  }

  .campaign-org,
  .campaign-dates {
    display: flex;
    align-items: center;
    gap: 0.375rem;
  }

  .campaign-bio {
    font-size: 0.9375rem;
    line-height: 1.6;
    color: var(--sidebar-text-muted);
    margin: 0;
  }

  .campaign-platforms {
    display: flex;
    gap: 0.5rem;
    flex-wrap: wrap;
  }

  .campaign-platform-tag {
    padding: 0.25rem 0.625rem;
    background: var(--sidebar-hover);
    border: 1px solid var(--sidebar-border);
    border-radius: 6px;
    font-size: 0.75rem;
    font-weight: 500;
    color: var(--sidebar-text);
  }

  /* Stats Grid */
  .campaign-stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 1rem;
  }

  .campaign-stat-card {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 1rem;
    background: var(--sidebar-hover);
    border: 1px solid var(--sidebar-border);
    border-radius: 12px;
  }

  .campaign-stat-card__icon {
    width: 40px;
    height: 40px;
    border-radius: 10px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .campaign-stat-card__icon--purple {
    background: rgba(147, 51, 234, 0.15);
    color: #9333ea;
  }

  .campaign-stat-card__icon--cyan {
    background: rgba(6, 182, 212, 0.15);
    color: #06b6d4;
  }

  .campaign-stat-card__icon--green {
    background: rgba(16, 185, 129, 0.15);
    color: #10b981;
  }

  .campaign-stat-card__icon--orange {
    background: rgba(245, 158, 11, 0.15);
    color: #f59e0b;
  }

  .campaign-stat-card__content {
    display: flex;
    flex-direction: column;
  }

  .campaign-stat-card__value {
    font-size: 1.25rem;
    font-weight: 700;
    color: var(--sidebar-text);
    line-height: 1.2;
  }

  .campaign-stat-card__label {
    font-size: 0.75rem;
    color: var(--sidebar-text-muted);
    text-transform: uppercase;
    letter-spacing: 0.03em;
  }

  /* Budget Card */
  .budget-card {
    background: var(--sidebar-bg);
    border: 1px solid var(--sidebar-border);
    border-radius: 12px;
    padding: 1.5rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .budget-card__header {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .budget-card__title {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.9375rem;
    font-weight: 600;
    color: var(--sidebar-text);
  }

  .budget-card__amount {
    font-size: 1rem;
    font-weight: 600;
    color: var(--sidebar-text);
  }

  .budget-card__bar {
    width: 100%;
    height: 8px;
    background-color: rgba(255, 255, 255, 0.05);
    border-radius: 4px;
    overflow: hidden;
    border: 1px solid var(--sidebar-border);
  }

  .budget-card__fill {
    height: 100%;
    border-radius: 3px;
    transition: width 400ms cubic-bezier(0.4, 0, 0.2, 1);
  }

  .budget-card__fill--low {
    background: linear-gradient(90deg, #10b981 0%, #059669 100%);
  }

  .budget-card__fill--medium {
    background: linear-gradient(90deg, #f59e0b 0%, #d97706 100%);
  }

  .budget-card__fill--high {
    background: linear-gradient(90deg, #ef4444 0%, #dc2626 100%);
  }

  .budget-card__footer {
    display: flex;
    justify-content: space-between;
    font-size: 0.8125rem;
    color: var(--sidebar-text-muted);
  }

  /* Tabs */
  .tabs-nav {
    background: var(--sidebar-bg);
    border: 1px solid var(--sidebar-border);
    border-radius: 12px;
    padding: 0.5rem;
  }

  .tabs-container {
    display: flex;
    gap: 0.5rem;
  }

  .tab-button {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    padding: 0.75rem 1rem;
    background: transparent;
    border: none;
    border-radius: 8px;
    color: var(--sidebar-text-muted);
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s;
  }

  .tab-button:hover {
    background: var(--sidebar-hover);
    color: var(--sidebar-text);
  }

  .tab-button--active {
    background: var(--sidebar-active);
    color: var(--sidebar-text);
  }

  .tab-button__icon {
    width: 18px;
    height: 18px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .tab-button__count {
    padding: 0.125rem 0.5rem;
    background: var(--sidebar-hover);
    border-radius: 12px;
    font-size: 0.75rem;
    font-weight: 600;
  }

  .tab-button--active .tab-button__count {
    background: var(--sidebar-bg);
  }

  /* Content */
  .content {
    background: var(--sidebar-bg);
    border: 1px solid var(--sidebar-border);
    border-radius: 12px;
    padding: 2rem;
  }

  .section-title {
    font-size: 1.125rem;
    font-weight: 600;
    color: var(--sidebar-text);
    margin: 0 0 1.5rem;
  }

  .details-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1.5rem;
  }

  .detail-item {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .detail-label {
    font-size: 0.8125rem;
    color: var(--sidebar-text-muted);
    text-transform: uppercase;
    letter-spacing: 0.03em;
  }

  .detail-value {
    font-size: 1rem;
    font-weight: 600;
    color: var(--sidebar-text);
  }

  /* Overview Section */
  .overview-section {
    margin-bottom: 1.5rem;
  }

  .overview-section:last-child {
    margin-bottom: 0;
  }

  /* Global Branding Notice */
  .global-branding-notice {
    display: flex;
    align-items: flex-start;
    gap: 1rem;
    padding: 1.5rem;
    background: rgba(59, 130, 246, 0.1);
    border: 1px solid rgba(59, 130, 246, 0.3);
    border-radius: 12px;
  }

  .global-branding-notice__icon {
    width: 48px;
    height: 48px;
    border-radius: 10px;
    background: rgba(59, 130, 246, 0.15);
    display: flex;
    align-items: center;
    justify-content: center;
    color: #3b82f6;
    flex-shrink: 0;
  }

  .global-branding-notice__content {
    flex: 1;
  }

  .global-branding-notice__title {
    font-size: 1rem;
    font-weight: 600;
    color: var(--sidebar-text);
    margin: 0 0 0.5rem;
  }

  .global-branding-notice__description {
    font-size: 0.875rem;
    line-height: 1.5;
    color: var(--sidebar-text-muted);
    margin: 0;
  }

  /* Streamers List */
  .streamers-list__description {
    font-size: 0.875rem;
    color: var(--sidebar-text-muted);
    margin: 0 0 1rem;
  }

  .streamers-list__placeholder {
    padding: 1rem;
    background: var(--sidebar-hover);
    border: 1px solid var(--sidebar-border);
    border-radius: 8px;
    text-align: center;
    color: var(--sidebar-text-muted);
    font-size: 0.875rem;
  }

  /* Placeholder States */
  .submissions-placeholder,
  .participants-placeholder,
  .payments-placeholder {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 4rem 2rem;
    gap: 1rem;
    color: var(--sidebar-text-muted);
  }

  .edit-btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.625rem 1.25rem;
    background: var(--sidebar-hover);
    border: 1px solid var(--sidebar-border);
    border-radius: 8px;
    color: var(--sidebar-text);
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s;
  }

  .edit-btn:hover {
    background: var(--sidebar-active);
  }

  .edit-btn__icon {
    width: 16px;
    height: 16px;
  }
</style>

// landing/src/pages/dashboard/CampaignDetailPage.tsx
import { useEffect, useState, useMemo } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { 
  Megaphone, 
  Building2, 
  Users, 
  FileVideo, 
  CheckCircle, 
  Wallet, 
  DollarSign, 
  TrendingUp, 
  Calendar,
  Globe,
  AlertCircle,
  Loader2
} from 'lucide-react'
import { api } from '@/lib/api'
import type { Campaign } from '@/types/organization'
import { Breadcrumbs } from '@/components/dashboard/Breadcrumbs'

interface CampaignStats {
  participants_count: number
  submissions_count: number
  verified_count: number
  total_views: number
  total_paid: string
}

export default function CampaignDetailPage() {
  const { orgId, campaignId } = useParams<{ orgId: string; campaignId: string }>()
  const navigate = useNavigate()
  const [loading, setLoading] = useState(true)
  const [campaign, setCampaign] = useState<Campaign | null>(null)
  const [stats] = useState<CampaignStats>({
    participants_count: 0,
    submissions_count: 0,
    verified_count: 0,
    total_views: 0,
    total_paid: '0',
  })
  const [activeTab, setActiveTab] = useState('overview')

  const breadcrumbItems = useMemo(() => [
    { label: 'Dashboard', to: '/dashboard' },
    { label: campaign?.organization?.name || 'Organization', to: `/dashboard/org/${orgId}` },
    { label: 'Campaigns', to: `/dashboard/org/${orgId}/campaigns` },
    { label: campaign?.title || 'Campaign' }
  ], [campaign, orgId])

  const tabs = [
    { id: 'overview', label: 'Overview', icon: Megaphone, count: undefined },
    { id: 'submissions', label: 'Submissions', icon: FileVideo, count: stats.submissions_count },
    { id: 'participants', label: 'Participants', icon: Users, count: stats.participants_count },
    { id: 'payments', label: 'Payments', icon: DollarSign, count: undefined },
  ]

  const formatBudget = (budget: string | number) => {
    const value = typeof budget === 'string' ? parseFloat(budget) : budget
    if (value >= 1000) {
      return `${(value / 1000).toFixed(1)}K`
    }
    return value.toFixed(0)
  }

  const formatCpm = (cpm: string | number) => {
    const value = typeof cpm === 'string' ? parseFloat(cpm) : cpm
    return value.toFixed(2)
  }

  const formatViews = (views: number) => {
    if (views >= 1000000) {
      return `${(views / 1000000).toFixed(1)}M`
    }
    if (views >= 1000) {
      return `${(views / 1000).toFixed(1)}K`
    }
    return views.toString()
  }

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr)
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
  }

  const getBudgetPercentage = () => {
    if (!campaign) return 0
    const spent = parseFloat(campaign.spent_budget || '0')
    const budget = parseFloat(campaign.budget || '0')
    if (budget === 0) return 0
    return Math.min((spent / budget) * 100, 100)
  }

  const getRemainingBudget = () => {
    if (!campaign) return 0
    const spent = parseFloat(campaign.spent_budget || '0')
    const budget = parseFloat(campaign.budget || '0')
    return Math.max(budget - spent, 0)
  }

  const getPlatformDisplayName = (platform: string): string => {
    const names: Record<string, string> = { 
      tiktok: 'TikTok', 
      instagram: 'Instagram', 
      x: 'X (Twitter)', 
      youtube: 'YouTube' 
    }
    return names[platform] || platform
  }

  useEffect(() => {
    const loadCampaign = async () => {
      try {
        setLoading(true)
        const response = await api.get<{ success: boolean; campaign?: Campaign }>(`/campaigns/${campaignId}`)
        if (response.success && response.campaign) {
          setCampaign(response.campaign)
        }
      } catch (error) {
        console.error('Failed to load campaign:', error)
      } finally {
        setLoading(false)
      }
    }

    if (campaignId) {
      loadCampaign()
    }
  }, [campaignId])

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
      </div>
    )
  }

  if (!campaign) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen gap-4 text-gray-400">
        <AlertCircle size={48} />
        <h3 className="text-xl font-semibold text-white">Campaign not found</h3>
        <p>The campaign you're looking for doesn't exist or you don't have access to it.</p>
        <button
          onClick={() => navigate(-1)}
          className="px-4 py-2 mt-4 bg-gray-800 border border-gray-700 rounded-lg hover:bg-gray-700"
        >
          Go Back
        </button>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        <Breadcrumbs items={breadcrumbItems} />
        {/* Header Card */}
        <div className="relative bg-gray-900 border border-gray-800 rounded-2xl overflow-hidden">
          <div className="absolute top-0 left-0 right-0 h-32 bg-gradient-to-br from-blue-500/10 to-purple-500/10 blur-xl opacity-30" />
          
          <div className="relative p-8 space-y-6">
            <div className="flex gap-6">
              <div className="flex-shrink-0">
                <div className="w-24 h-24 bg-gray-800 border-4 border-gray-900 rounded-2xl flex items-center justify-center">
                  {campaign.cover_image_url ? (
                    <img src={campaign.cover_image_url} alt={campaign.title} className="w-full h-full object-cover rounded-xl" />
                  ) : (
                    <Megaphone className="w-12 h-12 text-gray-600" />
                  )}
                </div>
              </div>

              <div className="flex-1 space-y-3">
                <div className="flex items-center gap-3 flex-wrap">
                  <h1 className="text-3xl font-bold">{campaign.title}</h1>
                  <div className="flex gap-2">
                    <span className={`px-3 py-1 rounded-lg text-xs font-semibold uppercase ${
                      campaign.status === 'active' ? 'bg-green-500/20 text-green-400 border border-green-500/30' :
                      campaign.status === 'draft' ? 'bg-gray-500/20 text-gray-400 border border-gray-500/30' :
                      campaign.status === 'paused' ? 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30' :
                      'bg-blue-500/20 text-blue-400 border border-blue-500/30'
                    }`}>
                      {campaign.status}
                    </span>
                    <span className="px-3 py-1 rounded-lg text-xs font-semibold bg-purple-500/20 text-purple-400 border border-purple-500/30">
                      {campaign.payment_model === 'per_clip' ? (
                        <><DollarSign className="inline w-3 h-3" /> Per Clip</>
                      ) : (
                        <><TrendingUp className="inline w-3 h-3" /> CPM</>
                      )}
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-4 text-sm text-gray-400">
                  {campaign.organization && (
                    <span className="flex items-center gap-2">
                      <Building2 size={14} />
                      {campaign.organization.name}
                    </span>
                  )}
                  {campaign.starts_at && (
                    <span className="flex items-center gap-2">
                      <Calendar size={14} />
                      {formatDate(campaign.starts_at)} - {campaign.ends_at ? formatDate(campaign.ends_at) : 'Ongoing'}
                    </span>
                  )}
                </div>

                <p className="text-gray-400">{campaign.description || 'No description provided'}</p>

                {campaign.allowed_platforms && campaign.allowed_platforms.length > 0 && (
                  <div className="flex gap-2 flex-wrap">
                    {campaign.allowed_platforms.map((platform) => (
                      <span key={platform} className="px-3 py-1 bg-gray-800 border border-gray-700 rounded-lg text-xs font-medium">
                        {getPlatformDisplayName(platform)}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="flex items-center gap-3 p-4 bg-gray-800/50 border border-gray-700 rounded-xl">
                <div className="w-10 h-10 bg-purple-500/20 rounded-lg flex items-center justify-center">
                  <Users size={18} className="text-purple-400" />
                </div>
                <div>
                  <div className="text-xl font-bold">{stats.participants_count || 0}</div>
                  <div className="text-xs text-gray-400 uppercase">Participants</div>
                </div>
              </div>

              <div className="flex items-center gap-3 p-4 bg-gray-800/50 border border-gray-700 rounded-xl">
                <div className="w-10 h-10 bg-cyan-500/20 rounded-lg flex items-center justify-center">
                  <FileVideo size={18} className="text-cyan-400" />
                </div>
                <div>
                  <div className="text-xl font-bold">{stats.submissions_count || 0}</div>
                  <div className="text-xs text-gray-400 uppercase">Submissions</div>
                </div>
              </div>

              <div className="flex items-center gap-3 p-4 bg-gray-800/50 border border-gray-700 rounded-xl">
                <div className="w-10 h-10 bg-green-500/20 rounded-lg flex items-center justify-center">
                  <CheckCircle size={18} className="text-green-400" />
                </div>
                <div>
                  <div className="text-xl font-bold">{stats.verified_count || 0}</div>
                  <div className="text-xs text-gray-400 uppercase">Verified</div>
                </div>
              </div>

              <div className="flex items-center gap-3 p-4 bg-gray-800/50 border border-gray-700 rounded-xl">
                <div className="w-10 h-10 bg-orange-500/20 rounded-lg flex items-center justify-center">
                  <Wallet size={18} className="text-orange-400" />
                </div>
                <div>
                  <div className="text-xl font-bold">${formatBudget(campaign.spent_budget || 0)}</div>
                  <div className="text-xs text-gray-400 uppercase">Spent</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Budget Progress */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 font-semibold">
              <Wallet size={18} />
              <span>Budget Usage</span>
            </div>
            <span className="text-sm font-semibold">
              ${formatBudget(campaign.spent_budget || 0)} / ${formatBudget(campaign.budget)}
            </span>
          </div>

          <div className="w-full h-2 bg-gray-800 rounded-full border border-gray-700 overflow-hidden">
            <div
              className={`h-full rounded-full transition-all ${
                getBudgetPercentage() < 50 ? 'bg-gradient-to-r from-green-500 to-green-600' :
                getBudgetPercentage() < 80 ? 'bg-gradient-to-r from-yellow-500 to-yellow-600' :
                'bg-gradient-to-r from-red-500 to-red-600'
              }`}
              style={{ width: `${getBudgetPercentage()}%` }}
            />
          </div>

          <div className="flex items-center justify-between text-sm text-gray-400">
            <span>${formatBudget(getRemainingBudget())} remaining</span>
            <span>{getBudgetPercentage().toFixed(1)}% used</span>
          </div>
        </div>

        {/* Tabs */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-2">
          <div className="flex gap-2">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg font-medium transition-all ${
                  activeTab === tab.id
                    ? 'bg-gray-800 text-white'
                    : 'text-gray-400 hover:bg-gray-800/50 hover:text-white'
                }`}
              >
                <tab.icon size={18} />
                <span>{tab.label}</span>
                {tab.count !== undefined && (
                  <span className={`px-2 py-0.5 rounded-full text-xs font-semibold ${
                    activeTab === tab.id ? 'bg-gray-900' : 'bg-gray-800'
                  }`}>
                    {tab.count}
                  </span>
                )}
              </button>
            ))}
          </div>
        </div>

        {/* Content */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-8">
          {activeTab === 'overview' && (
            <div className="space-y-8">
              <div>
                <h2 className="text-lg font-semibold mb-6">Campaign Details</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  <div>
                    <div className="text-xs text-gray-400 uppercase mb-2">Payment Model</div>
                    <div className="font-semibold">{campaign.payment_model === 'per_clip' ? 'Pay Per Clip' : 'CPM (Cost Per Mille)'}</div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-400 uppercase mb-2">{campaign.payment_model === 'per_clip' ? 'Amount Per Clip' : 'CPM Rate'}</div>
                    <div className="font-semibold">${campaign.payment_model === 'per_clip' ? formatBudget(campaign.per_clip_amount || 0) : formatCpm(campaign.cpm)}</div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-400 uppercase mb-2">Min Views for Payment</div>
                    <div className="font-semibold">{formatViews(campaign.min_views_for_payment)}</div>
                  </div>
                  {campaign.max_views && (
                    <div>
                      <div className="text-xs text-gray-400 uppercase mb-2">Max Views Cap</div>
                      <div className="font-semibold">{formatViews(campaign.max_views)}</div>
                    </div>
                  )}
                  <div>
                    <div className="text-xs text-gray-400 uppercase mb-2">Join Type</div>
                    <div className="font-semibold">{campaign.join_type === 'open' ? 'Open to All' : 'Application Required'}</div>
                  </div>
                </div>
              </div>

              <div>
                <h2 className="text-lg font-semibold mb-6">Streamers to Clip</h2>
                {!campaign.creator_profile_id && (!campaign.assigned_streamer_ids || campaign.assigned_streamer_ids.length === 0) ? (
                  <div className="flex items-start gap-4 p-6 bg-blue-500/10 border border-blue-500/30 rounded-xl">
                    <div className="w-12 h-12 bg-blue-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                      <Globe size={24} className="text-blue-400" />
                    </div>
                    <div>
                      <h3 className="font-semibold mb-2">Any Streamers Qualify</h3>
                      <p className="text-sm text-gray-400">
                        This campaign uses global branding. Clippers can create clips from any streamer, and the organization's branding will be applied automatically.
                      </p>
                    </div>
                  </div>
                ) : campaign.creator_profile_id ? (
                  <div>
                    <p className="text-sm text-gray-400 mb-4">This campaign is assigned to a specific creator profile:</p>
                    {campaign.creator_profile ? (
                      <div className="p-4 bg-gray-800 border border-gray-700 rounded-lg">
                        <div className="flex items-center gap-3">
                          {campaign.creator_profile.profile_image_url && (
                            <img src={campaign.creator_profile.profile_image_url} alt={campaign.creator_profile.name} className="w-12 h-12 rounded-full" />
                          )}
                          <div>
                            <div className="font-semibold">{campaign.creator_profile.name}</div>
                            <div className="text-sm text-gray-400">Creator Profile</div>
                          </div>
                        </div>
                      </div>
                    ) : (
                      <div className="p-4 bg-gray-800 border border-gray-700 rounded-lg text-center text-gray-400 text-sm">
                        Creator profile assigned
                      </div>
                    )}
                  </div>
                ) : (
                  <div>
                    <p className="text-sm text-gray-400 mb-4">Clippers can only create clips from the following streamers:</p>
                    <div className="p-4 bg-gray-800 border border-gray-700 rounded-lg text-center text-gray-400 text-sm">
                      {campaign.assigned_streamer_ids.length} streamer(s) assigned
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}

          {activeTab === 'submissions' && (
            <div className="flex flex-col items-center justify-center py-16 text-gray-400">
              <FileVideo size={48} />
              <p className="mt-4">Submissions management coming soon</p>
            </div>
          )}

          {activeTab === 'participants' && (
            <div className="flex flex-col items-center justify-center py-16 text-gray-400">
              <Users size={48} />
              <p className="mt-4">Participants list coming soon</p>
            </div>
          )}

          {activeTab === 'payments' && (
            <div className="flex flex-col items-center justify-center py-16 text-gray-400">
              <DollarSign size={48} />
              <p className="mt-4">Payments management coming soon</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
