// landing/src/components/dashboard/DashboardSidebar.tsx
import { Link, useParams, useLocation, useNavigate } from 'react-router-dom'
import {
  LayoutGrid,
  Users,
  UserCircle,
  Megaphone,
  Scissors,
  Share2,
  Globe,
  FileText,
  FolderOpen,
  CreditCard,
  Settings,
  LogOut,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { useAuth } from '@/hooks/useAuth'

interface NavItem {
  label: string
  icon: LucideIcon
  path: string
}

interface NavGroup {
  header: string
  items: NavItem[]
}

const navGroups: NavGroup[] = [
  {
    header: 'Team',
    items: [
      { label: 'Hub', icon: LayoutGrid, path: 'hub' },
      { label: 'Members', icon: Users, path: 'members' },
      { label: 'Creators', icon: UserCircle, path: 'creators' },
    ],
  },
  {
    header: 'Content',
    items: [
      { label: 'Campaigns', icon: Megaphone, path: 'campaigns' },
      { label: 'Clippers', icon: Scissors, path: 'clippers' },
      { label: 'Shared Clips', icon: Share2, path: 'shared' },
      { label: 'Social Accounts', icon: Globe, path: 'social' },
      { label: 'Posts', icon: FileText, path: 'posts' },
    ],
  },
  {
    header: 'Management',
    items: [
      { label: 'Assets', icon: FolderOpen, path: 'assets' },
      { label: 'Billing', icon: CreditCard, path: 'billing' },
      { label: 'Settings', icon: Settings, path: 'settings' },
    ],
  },
]

function getInitials(user: { name?: string; email: string }): string {
  if (user.name) {
    return user.name
      .split(' ')
      .map((w) => w[0])
      .join('')
      .toUpperCase()
      .slice(0, 2)
  }
  return user.email.slice(0, 2).toUpperCase()
}

export function DashboardSidebar() {
  const { id } = useParams<{ id: string }>()
  const location = useLocation()
  const navigate = useNavigate()
  const { user, logout } = useAuth()

  function isActive(path: string): boolean {
    const fullPath = `/dashboard/org/${id}/${path}`
    // Hub is also active for the index route
    if (path === 'hub') {
      return location.pathname === `/dashboard/org/${id}` || location.pathname === fullPath || location.pathname.startsWith(fullPath + '/')
    }
    return location.pathname === fullPath || location.pathname.startsWith(fullPath + '/')
  }

  function handleLogout() {
    logout()
    navigate('/')
  }

  return (
    <aside className="flex flex-col w-60 border-r border-zinc-800 bg-[#0a0a0b] shrink-0">
      {/* Logo */}
      <div className="p-3">
        <Link
          to="/"
          className="flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-zinc-800/50 transition-colors no-underline"
        >
          <img src="/logo-icon.svg" alt="Clippster" className="w-8 h-8 rounded-lg shrink-0" />
          <img src="/logo.svg" alt="Clippster" className="h-4" />
        </Link>
      </div>

      {/* Navigation */}
      <nav className="flex-1 overflow-y-auto overflow-x-hidden">
        <div className="flex flex-col p-3 gap-4">
          {navGroups.map((group, groupIndex) => (
            <div key={group.header} className="flex flex-col gap-1">
              {/* Group Label */}
              <div className="text-xs font-semibold uppercase tracking-wider text-zinc-500/70 pt-2 px-3 pb-1">
                {group.header}
              </div>

              {/* Navigation Items */}
              <ul className="list-none m-0 p-0 flex flex-col gap-0.5">
                {group.items.map((item) => {
                  const active = isActive(item.path)
                  const Icon = item.icon
                  return (
                    <li key={item.path}>
                      <Link
                        to={`/dashboard/org/${id}/${item.path}`}
                        className={`flex items-center gap-3 w-full py-2 px-3 rounded-md text-sm no-underline transition-all duration-150 cursor-pointer ${
                          active
                            ? 'bg-cyan-500/[0.08] text-cyan-400'
                            : 'text-zinc-500 hover:bg-zinc-800/50 hover:text-zinc-200'
                        }`}
                      >
                        <Icon className="w-[18px] h-[18px] shrink-0" />
                        <span className="flex-1 whitespace-nowrap overflow-hidden text-ellipsis">{item.label}</span>
                      </Link>
                    </li>
                  )
                })}
              </ul>
            </div>
          ))}
        </div>
      </nav>

      {/* Footer: User Profile */}
      <div className="border-t border-zinc-800 p-[0.3rem]">
        {user && (
          <div className="flex items-center gap-2 w-full py-2 px-2 rounded-md">
            {user.avatar_url ? (
              <img
                src={user.avatar_url}
                alt={user.name || user.email}
                className="w-7 h-7 rounded-[20px] object-cover shrink-0"
                referrerPolicy="no-referrer"
              />
            ) : (
              <div className="w-7 h-7 rounded-[20px] bg-cyan-400 flex items-center justify-center shrink-0">
                <span className="text-xs font-extrabold text-[#0a0a0b] uppercase">
                  {getInitials(user)}
                </span>
              </div>
            )}
            <span className="flex-1 text-xs text-left whitespace-nowrap overflow-hidden text-ellipsis text-zinc-500" title={user.email}>
              {user.email}
            </span>
            <button
              onClick={handleLogout}
              title="Sign out"
              className="p-1.5 rounded-md text-zinc-500 hover:text-white hover:bg-zinc-800 transition-colors cursor-pointer border-none bg-transparent"
            >
              <LogOut className="w-3.5 h-3.5" />
            </button>
          </div>
        )}
      </div>
    </aside>
  )
}

// client/src/components/DashboardSidebar.vue
<template>
  <aside class="fixed left-0 top-0 h-full w-64 bg-card border-r border-border">
    <!-- Logo/Brand -->
    <div class="h-16 px-6 flex items-center border-b border-border">
      <img src="/logo.svg" alt="Clippster" class="h-7 w-auto" />
    </div>

    <!-- Navigation -->
    <nav class="p-4">
      <ul class="space-y-1">
        <template v-for="(item, index) in navigationItems" :key="item.path">
          <!-- Category Label -->
          <li v-if="item.category && shouldShowCategory(item.category, index)" class="pt-4 pb-2 px-3">
            <span class="text-xs font-semibold text-muted-foreground uppercase tracking-wider">{{ item.category }}</span>
          </li>
          
          <!-- Navigation Item -->
          <li>
            <router-link
              :to="item.path"
              class="nav-link"
              :class="{ 'nav-link-active': isActive(item.path) }"
            >
              <svg 
                v-if="item.name === 'PumpFun'"
                xmlns="http://www.w3.org/2000/svg" 
                class="h-5 w-5" 
                :fill="isActive(item.path) ? 'white' : 'currentColor'" 
                viewBox="0 0 24 24"
              >
                <path :d="item.icon" />
              </svg>
              <svg 
                v-else
                xmlns="http://www.w3.org/2000/svg" 
                class="h-5 w-5" 
                fill="none" 
                viewBox="0 0 24 24" 
                stroke="currentColor"
              >
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" :d="item.icon" />
              </svg>
              <span>{{ item.name }}</span>
            </router-link>
          </li>
        </template>
      </ul>
    </nav>

    <!-- User info and logout at bottom -->
    <div class="absolute bottom-0 w-64 p-4 border-t border-border">
      <div class="flex items-center justify-between">
        <span class="font-mono text-xs text-primary">{{ formattedAddress }}</span>
        <button
          @click="handleDisconnect"
          class="disconnect-btn"
        >
          Disconnect
        </button>
      </div>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { useWallet } from '@/composables/useWallet'
import { navigationItems } from '@/config/navigation'

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()
const { formatAddress } = useWallet()

const isActive = (path: string) => {
  return route.path.startsWith(path)
}

const shouldShowCategory = (category: string, index: number) => {
  // Only show category label for the first item with that category
  if (index === 0) return true
  const previousItem = navigationItems[index - 1]
  return previousItem.category !== category
}

const formattedAddress = computed(() => formatAddress(authStore.walletAddress))

const handleDisconnect = () => {
  authStore.logout()
  router.push('/login')
}
</script>

<style scoped>
.nav-link {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.625rem 0.75rem;
  border-radius: 0.35rem;
  color: var(--muted-foreground);
  transition: all 0.2s;
}

.nav-link:hover {
  color: var(--foreground);
  background-color: var(--accent);
}

.nav-link-active {
  background-color: rgb(255 255 255 / 0.1);
  color: white;
  border-left: 3px solid rgb(255 255 255);
  padding-left: calc(0.75rem - 2px);
}

.nav-link-active:hover {
  background-color: rgb(255 255 255 / 0.15);
  color: rgb(255 255 255);
}

.disconnect-btn {
  padding: 0.375rem 0.625rem;
  font-size: 0.75rem;
  line-height: 1rem;
  color: rgb(239 68 68);
  border: 1px solid transparent;
  border-radius: 0.25rem;
  transition: all 0.2s;
  cursor: pointer;
}

.disconnect-btn:hover {
  color: rgb(248 113 113);
  border-color: rgb(248 113 113 / 0.3);
  background-color: rgb(248 113 113 / 0.05);
}
</style>
