// landing/src/components/ui/EmptyState.tsx
import type { LucideIcon } from 'lucide-react'

interface EmptyStateProps {
  icon: LucideIcon
  title: string
  description: string
  action?: React.ReactNode
}

export function EmptyState({ icon: Icon, title, description, action }: EmptyStateProps) {
  return (
    <div className="flex flex-col items-center justify-center py-16 px-4 text-center">
      <div className="w-16 h-16 rounded-2xl bg-zinc-800/50 flex items-center justify-center mb-4">
        <Icon className="w-8 h-8 text-cyan-400" />
      </div>
      <h3 className="text-lg font-semibold text-white mb-1">{title}</h3>
      <p className="text-sm text-zinc-500 max-w-sm mb-6">{description}</p>
      {action}
    </div>
  )
}

// client/src/components/EmptyState.vue
<template>
  <div class="flex flex-col items-center justify-center min-h-[calc(100vh-16rem)]">
    <div class="p-5 bg-muted rounded-full mb-6">
      <slot name="icon">
        <File class="h-16 w-16 text-muted-foreground" />
      </slot>
    </div>

    <h3 class="text-xl font-semibold text-foreground mb-2">{{ title }}</h3>

    <p class="text-muted-foreground mb-6">{{ description }}</p>
    <slot name="action">
      <button
        v-if="buttonText"
        @click="$emit('action')"
        class="px-5 py-2.5 bg-gradient-to-br from-purple-500/80 to-indigo-500/80 hover:from-purple-500/90 hover:to-indigo-500/90 text-white rounded-md font-medium shadow-sm transition-all"
      >
        {{ buttonText }}
      </button>
    </slot>
  </div>
</template>

<script setup lang="ts">
  import { File } from 'lucide-vue-next';

  defineProps<{
    title: string;
    description: string;
    buttonText?: string;
  }>();

  defineEmits<{
    action: [];
  }>();
</script>
